### ISSUE TITLE
Temperature sensor offset

### ISSUE THREAD

**Issue by butako** [Airlytix/configuration#9]
Hi! Thank you for creating such an awesome device, I just received mine today. 
I have noticed that the reported temperature is a few degrees warmer than ambient air. Using an IR temperature gun, I can tell that the ESP board is running warm (~28C). Is this heat interfering with the onboard temperature sensor? 
Or is the idea that I should tweak the offset value to compensate? 

Thanks

**Comment by mikenorgate** [comment]
The ESP32 does generate some heat that can impact the temperature readings, I've found the amount of heat generated varies depending on environmental factors, like how much energy it has to put into transmitting over wifi. From my testing I've found that the amount of added heat will stabalise once the ES1 has been running for a couple of hours.

The best option is to leave it running for a few hours and then tweak the offset value to match the ambient temperature, this should then give you accurate readings from then on

**Comment by butako** [comment]
Thanks for explaining
